name: Tests
run-name: Push by ${{ github.actor }}
on: [push]
jobs:
  pytest37:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install Dependencies
        run: pip install flake8 yapf pytest
      - name: Install aws-list-all
        run: python setup.py install
      - name: Check that aws-list-all --help works.
        run: aws_list_all --help
      - run: pytest -vvv aws_list_all
      - run: flake8 aws_list_all
      - run: yapf -d -r aws_list_all/
